include:
  - project: "devops/templates/gitlab-ci"
    ref: 0.25.0
    file: "/templates/.repo-check.yml"
  - project: "devops/templates/gitlab-ci"
    ref: 0.25.0
    file: "/templates/.sonarqube.yml"

ruff-linter:
  stage: check
  image: registry.gitlab.com/pipeline-components/ruff:0.27.0
  dependencies: []
  script:
    - ruff check .
    - ruff check . --output-format json --output-file ruff.json
    - ruff check . --output-format gitlab --output-file ruff.gitlab.json
  artifacts:
    when: on_success
    access: developer
    reports:
      codequality: ruff.gitlab.json
    paths:
      - ruff.json
      - ruff.gitlab.json
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

ruff-formatter:
  stage: check
  image: registry.gitlab.com/pipeline-components/ruff:0.27.0
  dependencies: []
  script:
    - pip install ruff
    - ruff format . --check
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

create-virtual-env:
  stage: dependencies
  image: amd64/python:3.13-slim-bookworm
  script: |
    if [ ! -f .venv/bin/activate ]; then
          python -m venv --upgrade-deps .venv
    fi
    source .venv/bin/activate
    python -m pip install -e .[test]
  artifacts:
    paths:
      - .venv
    expire_in: 30 minutes
    access: none
    when: on_success
  cache:
    key: mlops-builder-service-venv
    paths:
      - .venv
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

tests:
  stage: test
  image: amd64/python:3.13-slim-bookworm
  dependencies:
    - create-virtual-env
  script:
    - source .venv/bin/activate
    - pytest --junit-xml=junit-pytest.xml --cov=papai_unified_storage --cov=connections --cov-report="xml:coverage.xml" --cov-report="term" tests --tb=short --color=no -s --durations 0 --durations-min 1
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: on_success
    access: developer
    paths:
      - coverage.xml
      - junit-pytest.xml
    reports:
      junit:
        - junit-pytest.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

mypy:
  stage: analysis
  image: amd64/python:3.13-slim-bookworm
  dependencies:
    - create-virtual-env
  script:
    - source .venv/bin/activate
    - pip install mypy mypy-gitlab-code-quality
    - mypy --install-types --non-interactive -p src > mypy-output.txt || true
    - cat mypy-output.txt
    - mypy-gitlab-code-quality < mypy-output.txt > mypy.codequality.json
  allow_failure: true
  artifacts:
    when: on_success
    access: developer
    reports:
      codequality: mypy.codequality.json
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
