"""
Generate requirements/*.txt files from pyproject.toml.
script from scikit-image.
"""

import sys
from pathlib import Path
from typing import overload

try:  # standard module since Python 3.11
    import tomllib as toml
except ImportError:
    try:  # available for older Python via pip
        import tomli as toml  # type: ignore[no-redef]
    except ImportError:
        sys.exit("Please install `tomli` first: `pip install tomli`")

repo_dir = Path(__file__).parent.parent
header = [
    "# Generated with a pre-commit hook. Do not edit this file directly.",
    "# To change requirements, modify pyproject.toml and either:",
    "#   - run `python requirements/generate_requirements.py`",
    "#   - stage pyproject.toml `git add pyproject.toml` and run `pre-commit run generate_requirements`",
]


@overload
def requirement_file_name(keys: str) -> str: ...
@overload
def requirement_file_name(keys: list[str]) -> list[str]: ...


def requirement_file_name(keys: str | list[str]) -> str | list[str]:
    suffix = ".txt"
    return add_presuffix(keys, suffix=suffix)


@overload
def add_presuffix(bases: str, prefix: str = "", suffix: str = "") -> str: ...


@overload
def add_presuffix(bases: list[str], prefix: str = "", suffix: str = "") -> list[str]: ...


def add_presuffix(bases: str | list[str], prefix: str = "", suffix: str = "") -> str | list[str]:
    def str_presuffix(base: str) -> str:
        return f"{prefix}{base}{suffix}"

    if isinstance(bases, str):
        return str_presuffix(bases)

    return [str_presuffix(base) for base in bases]


def generate_requirement_file(name: str, req_list: list[str]) -> None:
    req_fname = repo_dir / "requirements" / requirement_file_name(name)
    req_fname.write_text("\n".join(header + req_list) + "\n")


def main() -> None:
    pyproject = toml.loads((repo_dir / "pyproject.toml").read_text())

    dependencies: dict[str, list[str]] = pyproject["project"]["optional-dependencies"]
    dependencies = dependencies | {"default": pyproject["project"]["dependencies"]}

    for key, opt_list in dependencies.items():
        generate_requirement_file(key, opt_list)

    generate_grouped_requirements(pyproject["dependency-groups"])


def generate_grouped_requirements(dependency_groups: dict[str, list[str]]):
    for group_name, group_list in dependency_groups.items():
        group_requirements_links = add_presuffix(group_list, prefix="-r ", suffix=".txt")
        generate_requirement_file(group_name, group_requirements_links)


if __name__ == "__main__":
    main()
